### PR TITLE
Simple console draw.

### PR DESCRIPTION
**Pull request by izhbi**

### CODE REVIEW

**Comment by izhbi** [comment]
Example - [http://i.imgur.com/XVpYEAW.png](http://i.imgur.com/XVpYEAW.png)

**Comment by mradermaxlol** [comment]
1) For what? And drop that Obama shit, the thing's gotta be abstract and related to the project somehow -_-
2) Isn't too complicated?
3) Nothing in common with the original source in terms of code structure, etc. (variable naming, code blocks placing and so on)

I'll look into it better in the following days, but right now I think that this is not mergeable.

**Comment by izhbi** [comment]
It's a beautiful piece of code, displaying a great man. Just merge it!

**Comment by mradermaxlol** [comment]
There's no reason for me to do that. Why?

**Pull request closed without merging**
